### ISSUE TITLE
line 8 import syslog not existing (i think)

### ISSUE THREAD

**Issue by Toni500github** [LopeKinz/PinkyDCHAck#1]
line 8 "import syslog" error already installed the requirements
![Immagine 2022-03-26 181847](https://user-images.githubusercontent.com/88878648/160250441-e214e9cf-7dfe-4eb5-8c8c-487076309b9e.png)

**Comment by LopeKinz** [comment]
> line 8 "import syslog" error already installed the requirements
> 
> ![Immagine 2022-03-26 181847](https://user-images.githubusercontent.com/88878648/160250441-e214e9cf-7dfe-4eb5-8c8c-487076309b9e.png)
> 
>  

type pip3 install syslog

**Comment by Toni500github** [comment]
Tried but nothing
